tools:
  - name: DuckDuckGo search
    description: Search the web for small snippets of information
    language: python
    entrypoint: search.py
    inputs_schema:
      type: object
      properties:
        query:
          description: The query to search on DuckDuckGo
          type: string
      required:
        - query
    outputs_schema:
      description: List of the summarized results
      type: array
      items:
        type: string
